<a href="https://colab.research.google.com/github/Arminismus/Deep-Learning-EXPS/blob/main/Linear_Regression_Student_Test_Score_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

import matplotlib.pyplot as plt

from tensorflow.keras.layers import Dense,Normalization

from tensorflow.keras import Sequential
import pandas as pd

In [ ]:
#import dataset:

#Student Test Score prediction:
data = pd.read_csv('/content/test_scores.csv')

In [ ]:
data

,school,school_setting,school_type,classroom,teaching_method,n_student,student_id,gender,lunch,pretest,posttest
0,ANKYI,Urban,Non-public,6OL,Standard,20.0,2FHT3,Female,Does not qualify,62.0,72.0
1,ANKYI,Urban,Non-public,6OL,Standard,20.0,3JIVH,Female,Does not qualify,66.0,79.0
2,ANKYI,Urban,Non-public,6OL,Standard,20.0,3XOWE,Male,Does not qualify,64.0,76.0
3,ANKYI,Urban,Non-public,6OL,Standard,20.0,556O0,Female,Does not qualify,61.0,77.0
4,ANKYI,Urban,Non-public,6OL,Standard,20.0,74LOE,Male,Does not qualify,64.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...
2128,ZOWMK,Urban,Public,ZBH,Standard,30.0,T8LSK,Female,Does not qualify,39.0,55.0
2129,ZOWMK,Urban,Public,ZBH,Standard,30.0,VNP26,Female,Qualifies for reduced/free lunch,38.0,46.0
2130,ZOWMK,Urban,Public,ZBH,Standard,30.0,YDR1Z,Female,Qualifies for reduced/free lunch,45.0,51.0
2131,ZOWMK,Urban,Public,ZBH,Standard,30.0,YUEIH,Male,Qualifies for reduced/free lunch,46.0,53.0
2132,ZOWMK,Urban,Public,ZBH,Standard,30.0,ZVCQ8,Male,Qualifies for reduced/free lunch,41.0,48.0

In [ ]:
data.drop('school',inplace = True,axis = 1)

In [ ]:
data.drop(['classroom','student_id'],inplace = True,axis = 1)
overhead = data

In [ ]:
def one_hot_encode(data,feature_values,feature):
  for value in feature_values:
    data[value] = (data[feature] == value)
    #make new values into ints:
    data[value] = data[value].replace({True:1,False:0})
  
  #remove original feature
  data.drop(feature,inplace = True,axis = 1)

In [ ]:
s = set()
for i in overhead['teaching_method']:
  if i not in s:
    s.add(i)
list(s)

['Experimental', 'Standard']

In [ ]:
feature = 'teaching_method'
feature_values = ['Experimental','Standard']

def find_values(data,feature):
  s = set()
  for i in data[feature]:
    if i not in s:
      s.add(i)
  return list(s)

feature_values = find_values(feature= 'teaching_method',data = overhead)

In [ ]:
one_hot_encode(data = overhead,feature = 'school_setting',feature_values = find_values(overhead,'school_setting'))

In [ ]:
one_hot_encode(data = overhead,feature = 'teaching_method',feature_values = feature_values)

In [ ]:
one_hot_encode(data = overhead,feature = 'gender',feature_values = find_values(overhead,'gender'))

In [ ]:
overhead.drop('Male',inplace = True,axis = 1)

In [ ]:
one_hot_encode(data = overhead,feature = 'lunch',feature_values = find_values(overhead,'lunch'))

In [ ]:
overhead.drop('Does not qualify',inplace = True,axis = 1)

In [ ]:
overhead

,school_type,n_student,pretest,posttest,Suburban,Rural,Urban,Experimental,Standard,Female,Qualifies for reduced/free lunch
0,Non-public,20.0,62.0,72.0,0,0,1,0,1,1,0
1,Non-public,20.0,66.0,79.0,0,0,1,0,1,1,0
2,Non-public,20.0,64.0,76.0,0,0,1,0,1,0,0
3,Non-public,20.0,61.0,77.0,0,0,1,0,1,1,0
4,Non-public,20.0,64.0,76.0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2128,Public,30.0,39.0,55.0,0,0,1,0,1,1,0
2129,Public,30.0,38.0,46.0,0,0,1,0,1,1,1
2130,Public,30.0,45.0,51.0,0,0,1,0,1,1,1
2131,Public,30.0,46.0,53.0,0,0,1,0,1,0,1
2132,Public,30.0,41.0,48.0,0,0,1,0,1,0,1

In [ ]:
overhead.rename(columns = {'Qualifies for reduced/free lunch':'Free Lunch'},inplace = True)

In [ ]:
overhead

,school_type,n_student,pretest,posttest,Suburban,Rural,Urban,Experimental,Standard,Female,Free Lunch
0,Non-public,20.0,62.0,72.0,0,0,1,0,1,1,0
1,Non-public,20.0,66.0,79.0,0,0,1,0,1,1,0
2,Non-public,20.0,64.0,76.0,0,0,1,0,1,0,0
3,Non-public,20.0,61.0,77.0,0,0,1,0,1,1,0
4,Non-public,20.0,64.0,76.0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2128,Public,30.0,39.0,55.0,0,0,1,0,1,1,0
2129,Public,30.0,38.0,46.0,0,0,1,0,1,1,1
2130,Public,30.0,45.0,51.0,0,0,1,0,1,1,1
2131,Public,30.0,46.0,53.0,0,0,1,0,1,0,1
2132,Public,30.0,41.0,48.0,0,0,1,0,1,0,1

In [ ]:
one_hot_encode(data = overhead,feature = 'school_type',feature_values = find_values(overhead,'school_type'))

In [ ]:
overhead.drop('Non-public',inplace = True,axis = 1)

In [ ]:
y = overhead.pop('posttest').to_numpy()

In [ ]:
overhead = overhead.to_numpy()

In [ ]:
y

array([72., 79., 76., ..., 51., 53., 48.])

In [ ]:
#let's Create our Neural Network: No test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(overhead,y,test_size = 0.2,random_state = 12)

In [ ]:
x_train

array([[17., 84.,  0., ...,  1.,  0.,  0.],
       [14., 57.,  0., ...,  0.,  0.,  0.],
       [25., 35.,  0., ...,  1.,  1.,  1.],
       ...,
       [23., 66.,  1., ...,  1.,  0.,  1.],
       [20., 54.,  0., ...,  1.,  1.,  0.],
       [30., 30.,  0., ...,  0.,  1.,  1.]])

In [ ]:
y_test

array([ 68.,  70.,  74.,  56.,  68.,  80.,  70.,  56.,  46.,  63.,  78.,
        41.,  77.,  52.,  75.,  87.,  53.,  91.,  68.,  88.,  75.,  52.,
        54.,  58.,  48.,  46.,  60.,  95.,  81.,  43.,  82.,  54.,  57.,
       100.,  86.,  47.,  55.,  57.,  62.,  38.,  45.,  91.,  55.,  82.,
        74.,  84.,  66.,  60.,  79.,  67.,  67.,  93.,  66.,  77.,  72.,
        46.,  61.,  76.,  61.,  42.,  90.,  51.,  82.,  57.,  58.,  70.,
        61.,  54.,  88.,  69.,  66.,  54.,  69.,  72.,  57.,  56.,  71.,
        83.,  51.,  56.,  60.,  58.,  46.,  67.,  55.,  48.,  67.,  66.,
        71.,  81.,  60.,  76.,  55.,  48.,  73.,  62.,  91.,  92.,  82.,
        42.,  71.,  82.,  56.,  51.,  52., 100.,  59.,  77.,  78.,  68.,
        65.,  78.,  93.,  67.,  80.,  78.,  88.,  46.,  76.,  48.,  88.,
        74.,  73.,  72.,  42.,  75.,  59.,  51.,  84.,  81.,  77.,  49.,
        81.,  55.,  75.,  69.,  93.,  77.,  73.,  58.,  49.,  95.,  61.,
        68.,  67.,  85.,  50.,  82.,  58.,  78.,  70.,  76.,  78.,  64.,
        71.,  91.,  69.,  78.,  69.,  56.,  83.,  71.,  56.,  58.,  93.,
        90.,  76.,  85.,  47.,  79.,  57.,  70.,  78.,  59.,  62.,  66.,
        72.,  72.,  58.,  54.,  68.,  72.,  52.,  79.,  73.,  54.,  71.,
        68.,  66.,  62.,  82.,  93.,  71.,  63.,  73.,  75.,  84.,  92.,
        71.,  73.,  61.,  58.,  62.,  57.,  64.,  67.,  68.,  43.,  78.,
        45.,  58.,  77.,  82.,  83.,  57.,  57.,  48.,  57.,  75.,  92.,
        71.,  59.,  61.,  80.,  47.,  83.,  53.,  94.,  90.,  63.,  82.,
        71.,  52.,  44.,  52.,  88.,  47.,  67.,  68.,  52.,  73.,  60.,
        68.,  79.,  91.,  78.,  80.,  66.,  76.,  80.,  59.,  80.,  62.,
        51.,  75.,  44.,  72.,  68.,  79.,  58.,  45.,  44.,  61.,  73.,
        47.,  64.,  56.,  78.,  72.,  87.,  81.,  81.,  96.,  55.,  56.,
        63.,  92.,  67.,  57.,  69.,  71.,  56.,  51.,  61.,  47.,  95.,
        71.,  51., 100.,  69.,  81.,  61.,  67.,  57.,  47.,  57.,  43.,
        74.,  59.,  59.,  50.,  63.,  57.,  41.,  68.,  71.,  62.,  54.,
        79.,  62.,  71.,  69.,  73.,  76.,  61.,  76.,  57.,  70.,  77.,
        73.,  64.,  61.,  80.,  43.,  73.,  70.,  81.,  68.,  90.,  72.,
        58.,  75.,  71.,  76.,  36.,  56.,  43.,  82.,  47.,  77.,  83.,
        64.,  85.,  54.,  53.,  52.,  52.,  73.,  39.,  52.,  55.,  58.,
        51.,  45.,  70.,  76.,  66.,  57.,  45.,  62.,  89.,  63.,  65.,
        49.,  78.,  51.,  71.,  54.,  95.,  73.,  54.,  59.,  69.,  57.,
        74.,  81.,  74.,  82.,  62.,  90.,  68.,  49.,  74.,  61.,  65.,
        65.,  67.,  49.,  79.,  53.,  98.,  44.,  93.,  49.,  69.,  40.,
        66.,  51.,  59.,  72.,  86.,  90.,  72.,  63.,  72.,  52.,  79.,
        76.,  80.,  45.,  43.,  63.,  47.,  91.,  62.,  79.,  60.,  81.,
        40.,  50.,  82.,  70.,  79.,  51.,  51.,  32.,  45.])

In [ ]:
#let's make the model and compile and fit it:
model = Sequential([
    Normalization(input_shape =(10,)),
    Dense(units = 14,activation = 'relu'),
    Dense(units = 3,activation = 'relu'),
    Dense(units = 1,activation = 'linear'),
])

In [ ]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 normalization_7 (Normalizat  (None, 10)               21
 ion)

 dense_16 (Dense)            (None, 14)                154

 dense_17 (Dense)            (None, 3)                 45

 dense_18 (Dense)            (None, 1)                 4

=================================================================
Total params: 224
Trainable params: 203
Non-trainable params: 21
_________________________________________________________________

In [ ]:
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),loss = 'mse',metrics=['accuracy'])

In [ ]:
#make the Pandas dataframe into a vector
model.fit(x_train,y_train,epochs = 200)

Epoch 1/200
54/54 [==============================] - 1s 2ms/step - loss: 2111.6606 - accuracy: 0.0000e+00
Epoch 2/200
54/54 [==============================] - 0s 2ms/step - loss: 49.4966 - accuracy: 0.0000e+00
Epoch 3/200
54/54 [==============================] - 0s 2ms/step - loss: 27.7705 - accuracy: 0.0000e+00
Epoch 4/200
54/54 [==============================] - 0s 2ms/step - loss: 19.9856 - accuracy: 0.0000e+00
Epoch 5/200
54/54 [==============================] - 0s 2ms/step - loss: 17.6142 - accuracy: 0.0000e+00
Epoch 6/200
54/54 [==============================] - 0s 2ms/step - loss: 15.6134 - accuracy: 0.0000e+00
Epoch 7/200
54/54 [==============================] - 0s 2ms/step - loss: 14.8783 - accuracy: 0.0000e+00
Epoch 8/200
54/54 [==============================] - 0s 2ms/step - loss: 14.2147 - accuracy: 0.0000e+00
Epoch 9/200
54/54 [==============================] - 0s 2ms/step - loss: 13.6406 - accuracy: 0.0000e+00
Epoch 10/200
54/54 [==============================] - 0s 2ms/step - loss: 12.8863 - accuracy: 0.0000e+00
Epoch 11/200
54/54 [==============================] - 0s 2ms/step - loss: 12.5662 - accuracy: 0.0000e+00
Epoch 12/200
54/54 [==============================] - 0s 2ms/step - loss: 12.5593 - accuracy: 0.0000e+00
Epoch 13/200
54/54 [==============================] - 0s 2ms/step - loss: 12.5216 - accuracy: 0.0000e+00
Epoch 14/200
54/54 [==============================] - 0s 2ms/step - loss: 12.1177 - accuracy: 0.0000e+00
Epoch 15/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8640 - accuracy: 0.0000e+00
Epoch 16/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8525 - accuracy: 0.0000e+00
Epoch 17/200
54/54 [==============================] - 0s 2ms/step - loss: 12.0626 - accuracy: 0.0000e+00
Epoch 18/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8740 - accuracy: 0.0000e+00
Epoch 19/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8761 - accuracy: 0.0000e+00
Epoch 20/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8121 - accuracy: 0.0000e+00
Epoch 21/200
54/54 [==============================] - 0s 2ms/step - loss: 12.0806 - accuracy: 0.0000e+00
Epoch 22/200
54/54 [==============================] - 0s 2ms/step - loss: 11.9740 - accuracy: 0.0000e+00
Epoch 23/200
54/54 [==============================] - 0s 2ms/step - loss: 11.6379 - accuracy: 0.0000e+00
Epoch 24/200
54/54 [==============================] - 0s 2ms/step - loss: 11.6252 - accuracy: 0.0000e+00
Epoch 25/200
54/54 [==============================] - 0s 2ms/step - loss: 12.1033 - accuracy: 0.0000e+00
Epoch 26/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8626 - accuracy: 0.0000e+00
Epoch 27/200
54/54 [==============================] - 0s 2ms/step - loss: 11.7924 - accuracy: 0.0000e+00
Epoch 28/200
54/54 [==============================] - 0s 2ms/step - loss: 11.8864 - accuracy: 0.0000e+00
Epoch 29/200
54/54 [==============================] - 0s 2ms/step - loss: 11.3967 - accuracy: 0.0000e+00
Epoch 30/200
54/54 [==============================] - 0s 2ms/step - loss: 11.5744 - accuracy: 0.0000e+00
Epoch 31/200
54/54 [==============================] - 0s 2ms/step - loss: 11.6045 - accuracy: 0.0000e+00
Epoch 32/200
54/54 [==============================] - 0s 2ms/step - loss: 11.6457 - accuracy: 0.0000e+00
Epoch 33/200
54/54 [==============================] - 0s 2ms/step - loss: 11.1837 - accuracy: 0.0000e+00
Epoch 34/200
54/54 [==============================] - 0s 2ms/step - loss: 11.2581 - accuracy: 0.0000e+00
Epoch 35/200
54/54 [==============================] - 0s 2ms/step - loss: 11.4416 - accuracy: 0.0000e+00
Epoch 36/200
54/54 [==============================] - 0s 2ms/step - loss: 11.7739 - accuracy: 0.0000e+00
Epoch 37/200
54/54 [==============================] - 0s 2ms/step - loss: 11.1566 - accuracy: 0.0000e+00
Epoch 38/200
54/54 [==============================] - 0s 2ms/step - loss: 11.3688 - accuracy: 0.0000e+00
Epoch 39/200
54/54 [==============================] - 0s 2ms/step - loss: 11.4329 - accuracy: 0.0000e+00
Epoch 40/200
54/54 [==============================] - 0s 2ms/step - loss: 11.5991 - accuracy: 0.0000e+00
Epoch 41/200
54/54 [==============================] - 0s 2ms/step - loss: 11.1741 - accuracy: 0.0000e+00
Epoch 42/200
54/54 [==============================] - 0s 2ms/step - loss: 11.4360 - accuracy: 0.0000e+00
Epoch 43/200
54/54 [==============================] - 0s 2ms/step - loss: 11.2715 - accuracy: 0.0000e+00
Epoch 44/200
54/54 [==============================] - 0s 2ms/step - loss: 11.9112 - accuracy: 0.0000e+00
Epoch 45/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9548 - accuracy: 0.0000e+00
Epoch 46/200
54/54 [==============================] - 0s 2ms/step - loss: 11.1901 - accuracy: 0.0000e+00
Epoch 47/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9922 - accuracy: 0.0000e+00
Epoch 48/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6734 - accuracy: 0.0000e+00
Epoch 49/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9305 - accuracy: 0.0000e+00
Epoch 50/200
54/54 [==============================] - 0s 2ms/step - loss: 11.0015 - accuracy: 0.0000e+00
Epoch 51/200
54/54 [==============================] - 0s 2ms/step - loss: 11.2129 - accuracy: 0.0000e+00
Epoch 52/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7759 - accuracy: 0.0000e+00
Epoch 53/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7404 - accuracy: 0.0000e+00
Epoch 54/200
54/54 [==============================] - 0s 2ms/step - loss: 11.3231 - accuracy: 0.0000e+00
Epoch 55/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9450 - accuracy: 0.0000e+00
Epoch 56/200
54/54 [==============================] - 0s 2ms/step - loss: 11.0012 - accuracy: 0.0000e+00
Epoch 57/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7044 - accuracy: 0.0000e+00
Epoch 58/200
54/54 [==============================] - 0s 2ms/step - loss: 11.7191 - accuracy: 0.0000e+00
Epoch 59/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6175 - accuracy: 0.0000e+00
Epoch 60/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9065 - accuracy: 0.0000e+00
Epoch 61/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9789 - accuracy: 0.0000e+00
Epoch 62/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7392 - accuracy: 0.0000e+00
Epoch 63/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6428 - accuracy: 0.0000e+00
Epoch 64/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2868 - accuracy: 0.0000e+00
Epoch 65/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7602 - accuracy: 0.0000e+00
Epoch 66/200
54/54 [==============================] - 0s 2ms/step - loss: 11.1749 - accuracy: 0.0000e+00
Epoch 67/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4544 - accuracy: 0.0000e+00
Epoch 68/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1126 - accuracy: 0.0000e+00
Epoch 69/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1330 - accuracy: 0.0000e+00
Epoch 70/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0823 - accuracy: 0.0000e+00
Epoch 71/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3366 - accuracy: 0.0000e+00
Epoch 72/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3380 - accuracy: 0.0000e+00
Epoch 73/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9937 - accuracy: 0.0000e+00
Epoch 74/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2667 - accuracy: 0.0000e+00
Epoch 75/200
54/54 [==============================] - 0s 2ms/step - loss: 10.5597 - accuracy: 0.0000e+00
Epoch 76/200
54/54 [==============================] - 0s 2ms/step - loss: 11.5772 - accuracy: 0.0000e+00
Epoch 77/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4069 - accuracy: 0.0000e+00
Epoch 78/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2211 - accuracy: 0.0000e+00
Epoch 79/200
54/54 [==============================] - 0s 2ms/step - loss: 11.4549 - accuracy: 0.0000e+00
Epoch 80/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7386 - accuracy: 0.0000e+00
Epoch 81/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0587 - accuracy: 0.0000e+00
Epoch 82/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3481 - accuracy: 0.0000e+00
Epoch 83/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7250 - accuracy: 0.0000e+00
Epoch 84/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4178 - accuracy: 0.0000e+00
Epoch 85/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7788 - accuracy: 0.0000e+00
Epoch 86/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1678 - accuracy: 0.0000e+00
Epoch 87/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0292 - accuracy: 0.0000e+00
Epoch 88/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4140 - accuracy: 0.0000e+00
Epoch 89/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0284 - accuracy: 0.0000e+00
Epoch 90/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4221 - accuracy: 0.0000e+00
Epoch 91/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3809 - accuracy: 0.0000e+00
Epoch 92/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4577 - accuracy: 0.0000e+00
Epoch 93/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3333 - accuracy: 0.0000e+00
Epoch 94/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0508 - accuracy: 0.0000e+00
Epoch 95/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1945 - accuracy: 0.0000e+00
Epoch 96/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2331 - accuracy: 0.0000e+00
Epoch 97/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0908 - accuracy: 0.0000e+00
Epoch 98/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0473 - accuracy: 0.0000e+00
Epoch 99/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0541 - accuracy: 0.0000e+00
Epoch 100/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0423 - accuracy: 0.0000e+00
Epoch 101/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3914 - accuracy: 0.0000e+00
Epoch 102/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1801 - accuracy: 0.0000e+00
Epoch 103/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8658 - accuracy: 0.0000e+00
Epoch 104/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9168 - accuracy: 0.0000e+00
Epoch 105/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6021 - accuracy: 0.0000e+00
Epoch 106/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0538 - accuracy: 0.0000e+00
Epoch 107/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1939 - accuracy: 0.0000e+00
Epoch 108/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9439 - accuracy: 0.0000e+00
Epoch 109/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3276 - accuracy: 0.0000e+00
Epoch 110/200
54/54 [==============================] - 0s 2ms/step - loss: 10.7062 - accuracy: 0.0000e+00
Epoch 111/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1057 - accuracy: 0.0000e+00
Epoch 112/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0927 - accuracy: 0.0000e+00
Epoch 113/200
54/54 [==============================] - 0s 2ms/step - loss: 10.8958 - accuracy: 0.0000e+00
Epoch 114/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8647 - accuracy: 0.0000e+00
Epoch 115/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2174 - accuracy: 0.0000e+00
Epoch 116/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8972 - accuracy: 0.0000e+00
Epoch 117/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9715 - accuracy: 0.0000e+00
Epoch 118/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0021 - accuracy: 0.0000e+00
Epoch 119/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9195 - accuracy: 0.0000e+00
Epoch 120/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0849 - accuracy: 0.0000e+00
Epoch 121/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9920 - accuracy: 0.0000e+00
Epoch 122/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4998 - accuracy: 0.0000e+00
Epoch 123/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1139 - accuracy: 0.0000e+00
Epoch 124/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4002 - accuracy: 0.0000e+00
Epoch 125/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1465 - accuracy: 0.0000e+00
Epoch 126/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2281 - accuracy: 0.0000e+00
Epoch 127/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0821 - accuracy: 0.0000e+00
Epoch 128/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3095 - accuracy: 0.0000e+00
Epoch 129/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1194 - accuracy: 0.0000e+00
Epoch 130/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3530 - accuracy: 0.0000e+00
Epoch 131/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0992 - accuracy: 0.0000e+00
Epoch 132/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0362 - accuracy: 0.0000e+00
Epoch 133/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8892 - accuracy: 0.0000e+00
Epoch 134/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1946 - accuracy: 0.0000e+00
Epoch 135/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1115 - accuracy: 0.0000e+00
Epoch 136/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1392 - accuracy: 0.0000e+00
Epoch 137/200
54/54 [==============================] - 0s 2ms/step - loss: 9.7698 - accuracy: 0.0000e+00
Epoch 138/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0233 - accuracy: 0.0000e+00
Epoch 139/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0382 - accuracy: 0.0000e+00
Epoch 140/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6593 - accuracy: 0.0000e+00
Epoch 141/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2280 - accuracy: 0.0000e+00
Epoch 142/200
54/54 [==============================] - 0s 2ms/step - loss: 10.5662 - accuracy: 0.0000e+00
Epoch 143/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9926 - accuracy: 0.0000e+00
Epoch 144/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9000 - accuracy: 0.0000e+00
Epoch 145/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0810 - accuracy: 0.0000e+00
Epoch 146/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8965 - accuracy: 0.0000e+00
Epoch 147/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3346 - accuracy: 0.0000e+00
Epoch 148/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0581 - accuracy: 0.0000e+00
Epoch 149/200
54/54 [==============================] - 0s 2ms/step - loss: 10.8033 - accuracy: 0.0000e+00
Epoch 150/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2697 - accuracy: 0.0000e+00
Epoch 151/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1478 - accuracy: 0.0000e+00
Epoch 152/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9165 - accuracy: 0.0000e+00
Epoch 153/200
54/54 [==============================] - 0s 2ms/step - loss: 10.9259 - accuracy: 0.0000e+00
Epoch 154/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9426 - accuracy: 0.0000e+00
Epoch 155/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3248 - accuracy: 0.0000e+00
Epoch 156/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8838 - accuracy: 0.0000e+00
Epoch 157/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2999 - accuracy: 0.0000e+00
Epoch 158/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8729 - accuracy: 0.0000e+00
Epoch 159/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3976 - accuracy: 0.0000e+00
Epoch 160/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1140 - accuracy: 0.0000e+00
Epoch 161/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6117 - accuracy: 0.0000e+00
Epoch 162/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2945 - accuracy: 0.0000e+00
Epoch 163/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3740 - accuracy: 0.0000e+00
Epoch 164/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0436 - accuracy: 0.0000e+00
Epoch 165/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9738 - accuracy: 0.0000e+00
Epoch 166/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0783 - accuracy: 0.0000e+00
Epoch 167/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2805 - accuracy: 0.0000e+00
Epoch 168/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9672 - accuracy: 0.0000e+00
Epoch 169/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9568 - accuracy: 0.0000e+00
Epoch 170/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0598 - accuracy: 0.0000e+00
Epoch 171/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0591 - accuracy: 0.0000e+00
Epoch 172/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0444 - accuracy: 0.0000e+00
Epoch 173/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1346 - accuracy: 0.0000e+00
Epoch 174/200
54/54 [==============================] - 0s 2ms/step - loss: 9.8907 - accuracy: 0.0000e+00
Epoch 175/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1055 - accuracy: 0.0000e+00
Epoch 176/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9877 - accuracy: 0.0000e+00
Epoch 177/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9962 - accuracy: 0.0000e+00
Epoch 178/200
54/54 [==============================] - 0s 2ms/step - loss: 10.6815 - accuracy: 0.0000e+00
Epoch 179/200
54/54 [==============================] - 0s 2ms/step - loss: 10.8523 - accuracy: 0.0000e+00
Epoch 180/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1055 - accuracy: 0.0000e+00
Epoch 181/200
54/54 [==============================] - 0s 2ms/step - loss: 10.1404 - accuracy: 0.0000e+00
Epoch 182/200
54/54 [==============================] - 0s 2ms/step - loss: 10.0543 - accuracy: 0.0000e+00
Epoch 183/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9103 - accuracy: 0.0000e+00
Epoch 184/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9042 - accuracy: 0.0000e+00
Epoch 185/200
54/54 [==============================] - 0s 2ms/step - loss: 9.9278 - accuracy: 0.0000e+00
Epoch 186/200
54/54 [==============================] - 0s 2ms/step - loss: 10.2192 - accuracy: 0.0000e+00
Epoch 187/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3775 - accuracy: 0.0000e+00
Epoch 188/200
54/54 [==============================] - 0s 2ms/step - loss: 10.4173 - accuracy: 0.0000e+00
Epoch 189/200
54/54 [==============================] - 0s 2ms/step - loss: 10.3360 - accuracy: 0.0000e+00
Epoch 190/200

In [ ]:
n = 0
model.predict(x_test[n]),y_test[n]

(array([[78.87812]], dtype=float32), 80.0)

In [ ]:
model.evaluate(x_test,y_test)

14/14 [==============================] - 0s 3ms/step - loss: 13.1502 - accuracy: 0.0000e+00

[13.150179862976074, 0.0]

In [ ]:
x_test[1]

array([27., 63.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.])

In [ ]:
model.predict([27,63,1,0,0,0,1,1,0,1])

array([[467.20676]], dtype=float32)